### ISSUE TITLE
dotfilesで管理するファイルのリストをYAMLファイルに記述する

### ISSUE THREAD

**Issue by nepia0318** [nepia0318/dotfiles#9]
# Purpose

- リストで一括でdotfilesの情報を管理したい
- 以下のような形式のYAMLファイルを想定

``` yaml
softwares:
  - name: bat
    directories:
      - path: ${HOME}/.config/bat
        files:
          - config
  - name: nvim
    directories:
      - path: ${HOME}/.config/nvim
        files:
          - init.lua
      - path: ${HOME}/.config/nvim/lua
        files:
          - base.lua
          - setup_plugin.lua
```

# ToDo

- 指定して追記できるようようなCLIツールをつくる
